In [1]:
!pip install numpy

In [4]:
import numpy as np

### 1. Create

In [67]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [7]:
data

array([[[0.23273757, 0.42732452, 0.50927928, 0.35936257],
        [0.71586106, 0.01249702, 0.22306449, 0.35065396],
        [0.04165257, 0.75534352, 0.33981221, 0.1591308 ]],

       [[0.29162832, 0.73676933, 0.36660353, 0.92162568],
        [0.39039869, 0.41728576, 0.22162457, 0.06912174],
        [0.13202048, 0.5868804 , 0.19740119, 0.47593857]]])

In [68]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### 2. Read

In [11]:
shape = data.shape
size = data.size
types = data.dtype

In [12]:
shape

(2, 3, 4)

In [13]:
size

24

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [16]:
singlevel

0.23273757326949285

In [17]:
data

array([[[0.23273757, 0.42732452, 0.50927928, 0.35936257],
        [0.71586106, 0.01249702, 0.22306449, 0.35065396],
        [0.04165257, 0.75534352, 0.33981221, 0.1591308 ]],

       [[0.29162832, 0.73676933, 0.36660353, 0.92162568],
        [0.39039869, 0.41728576, 0.22162457, 0.06912174],
        [0.13202048, 0.5868804 , 0.19740119, 0.47593857]]])

### 3. Update

In [18]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [19]:
list1

array([0.27307936, 0.5268827 , 0.29325328, 0.87836888, 0.46046832,
       0.0682031 , 0.06420509, 0.56921008, 0.03405547, 0.68433122])

In [20]:
list2

array([0.34920684, 0.6491157 , 0.78281388, 0.36420899, 0.67162121,
       0.51119479, 0.61611527, 0.19801558, 0.41101445, 0.69047415])

In [22]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [23]:
add

array([0.6222862 , 1.17599839, 1.07606716, 1.24257787, 1.13208954,
       0.57939789, 0.68032036, 0.76722567, 0.44506992, 1.37480538])

In [24]:
sub

array([-0.07612748, -0.122233  , -0.48956059,  0.5141599 , -0.21115289,
       -0.44299169, -0.55191018,  0.3711945 , -0.37695897, -0.00614293])

In [25]:
div

array([0.78199889, 0.81169304, 0.37461431, 2.41171667, 0.68560717,
       0.133419  , 0.10420955, 2.87457218, 0.08285712, 0.99110332])

In [26]:
mult

array([0.09536118, 0.34200783, 0.22956274, 0.31990984, 0.30926029,
       0.03486507, 0.03955774, 0.11271247, 0.01399729, 0.47251302])

In [27]:
dot

1.9697474719017483

In [28]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp((2,3))
mins = np.min(list1)
maxs = np.max(list1)

In [29]:
sqrt

5.0

In [30]:
ab

2

In [31]:
power

128

In [32]:
log

3.2188758248682006

In [33]:
exp

array([ 7.3890561 , 20.08553692])

In [34]:
mins

0.03405547387173247

In [35]:
maxs

0.8783688848325488

In [36]:
data

array([[[0.23273757, 0.42732452, 0.50927928, 0.35936257],
        [0.71586106, 0.01249702, 0.22306449, 0.35065396],
        [0.04165257, 0.75534352, 0.33981221, 0.1591308 ]],

       [[0.29162832, 0.73676933, 0.36660353, 0.92162568],
        [0.39039869, 0.41728576, 0.22162457, 0.06912174],
        [0.13202048, 0.5868804 , 0.19740119, 0.47593857]]])

In [38]:
data.sort()
data

array([[[0.23273757, 0.35936257, 0.42732452, 0.50927928],
        [0.01249702, 0.22306449, 0.35065396, 0.71586106],
        [0.04165257, 0.1591308 , 0.33981221, 0.75534352]],

       [[0.29162832, 0.36660353, 0.73676933, 0.92162568],
        [0.06912174, 0.22162457, 0.39039869, 0.41728576],
        [0.13202048, 0.19740119, 0.47593857, 0.5868804 ]]])

In [48]:
data = data.reshape((2,2,-1))   # '-1' in third position means we don't care shape of columns, auto-calculate to 6 columns
print(data.shape)
print(data)

(2, 2, 6)
[[[0.23273757 0.35936257 0.42732452 0.50927928 0.01249702 0.22306449]
  [0.35065396 0.71586106 0.04165257 0.1591308  0.33981221 0.75534352]]

 [[0.29162832 0.36660353 0.73676933 0.92162568 0.06912174 0.22162457]
  [0.39039869 0.41728576 0.13202048 0.19740119 0.47593857 0.5868804 ]]]


In [51]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [52]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


### 4. Delete

In [53]:
data

array([[[0.23273757, 0.35936257, 0.42732452, 0.50927928, 0.01249702,
         0.22306449],
        [0.35065396, 0.71586106, 0.04165257, 0.1591308 , 0.33981221,
         0.75534352]],

       [[0.29162832, 0.36660353, 0.73676933, 0.92162568, 0.06912174,
         0.22162457],
        [0.39039869, 0.41728576, 0.13202048, 0.19740119, 0.47593857,
         0.5868804 ]]])

In [54]:
np.delete(data, 0, axis=1)   # axis=1 means we want to delete row, not column

array([[[0.35065396, 0.71586106, 0.04165257, 0.1591308 , 0.33981221,
         0.75534352]],

       [[0.39039869, 0.41728576, 0.13202048, 0.19740119, 0.47593857,
         0.5868804 ]]])

In [56]:
#np.save("new array", data)
#test = np.load("new array.npy")
#test

### 5. Other

In [66]:
one_dim = np.array([1,2,3])
print("One Dim Array: \n", one_dim)
print("One Dim: \n", one_dim.ndim)   # Prints the dimension of a given array

two_dim = np.array([[1,2,3], [4,5,6]])
print("Two Dim Array: \n", two_dim)
print("Two Dim: \n", two_dim.ndim)

three_dim = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print("Three Dim Array: \n", three_dim)
print("Three Dim: \n", three_dim.ndim)

# Give an array any dimension you want
new_array = np.array([1,2], ndmin=5)
print("New Array: \n", new_array)

One Dim Array: 
 [1 2 3]
One Dim: 
 1
Two Dim Array: 
 [[1 2 3]
 [4 5 6]]
Two Dim: 
 2
Three Dim Array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Three Dim: 
 3
New Array: 
 [[[[[1 2]]]]]
